### ISSUE TITLE
Unable to add user authentication

### ISSUE THREAD

**Issue by 4abhinavjain** [lucapisciotta/calibre#2]
Ciao Luca,

Thanks for preparing this arm64 version. I would like to enable user authentication as I am running this on internet arm server. So far I 
 have not been able to do so successfully. Could you please highlight how this can be done?

**Comment by lucapisciotta** [comment]
Hi, 
Yes, i'm using it on my raspberry but under a VPN so i didn't enabled the user authentication, do you already have a database with users?

**Comment by 4abhinavjain** [comment]
Yes, I already have a database with users. It will be a good addon if that could be added. Thanks

**Comment by redtomaka** [comment]
Hi Luca, I'am interested too in the user authentication feature. I am also running it on a raspberry but would like to avoid making others to configure a vpn client. Thanks a lot

**Comment by lucapisciotta** [comment]
Don't worry, i'll work on it in these days

**Comment by redtomaka** [comment]
Hi Luca I also see that annotations & highlights are not actually written back to the epub file.
So if I access the same library from calibre client I don't find them.
Looking at the container logs, I see that the server receives an HTTP POST, but I don't know where the annotation is being saved. IT is saved somewhere because if I reopen the book after a container restart, I can see it. That's weird :)

`POST /book-update-annotations/books/2/EPUB HTTP/1.1" HTTPStatus.OK 146`

**Comment by redtomaka** [comment]
Thank you very much! Users also turns out to be required in order to sync annotations and highlights cross-device :)

**Comment by lucapisciotta** [comment]
Hi @redtomaka, @4abhinavjain i've added the possibility to add the authentication and to test with an example database, i switched to the official package on `ubuntu:22.04` that has the latest official release but using it i encountered a problem related to the zeroconf package that is old on the ubuntu repository, can you check if this solved your problems?

**Comment by redtomaka** [comment]
Thank you, works like a charm! I've just tested it and found no problems so far, thank you very much.

**Comment by 4abhinavjain** [comment]
Thanks, Luca for the effort. It works well now
